config/routes.rb
Rails.application.routes.draw do
 root "cocktails#index"


mount Attachinary::Engine => "/attachinary"
 delete 'doses/:id', to: "doses#destroy", as: "delete_dose"
 delete "cocktails/:id", to: "cocktails#destroy", as: "delete_cocktail"
  resources :cocktails do
    resources :doses
  # , only: [:show, :index, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, dependent: :destroy, through: :doses
  has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: {scope: :cocktail}
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :cocktails, through: :doses
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end


  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path(@cocktail)
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to root_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
   @dose = Dose.new(dose_params)
   @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
    redirect_to cocktail_path(@dose.cocktail)
    else
    render :new
    end
  end

  def show
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo.path, height: 300, width: 400, crop: :fill %>')">
    <h2><%= cocktail.name%></h2>
  </div>
  <a class="card-link" href="#" ></a>
  <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
 <%= f.error_notification %>
 <div class='row'>
 <div class="form-inputs col-xs-6 col-md-6 col-lg-6 col-md-offset-3">
   <%= f.input :name %><br>
   <p><%= f.input :photo, as: :attachinary %></p>
   <%= f.button :submit, class: "btn btn-primary" %>
 </div>
 </div>
<% end %>

app/views/cocktails/index.html.erb
<body>
  <div class="banner" style="background-image: url('https://image.freepik.com/free-photo/watermelon-juice-with-copy-space_23-2147640789.jpg');">
    <div class="banner-content">
      <div class=“container”>
      <div class=“row”>
        <% @cocktails.each do |c| %>
        <div class="col-xs-12 col-sm-4">
          <%= render "card", cocktail: c %>
        <%#= link_to c.name, cocktail_path(c)%>
        </div>
        <% end%>
      </div>
      </div>

    </div>
  </div>
</body>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: url('https://image.freepik.com/free-photo/watermelon-juice-with-copy-space_23-2147640789.jpg');">
  <%= render 'form' %>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: url('https://image.freepik.com/free-photo/watermelon-juice-with-copy-space_23-2147640789.jpg');">
<div class="card-1" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @cocktail.photo.path, height: 300, width: 400, crop: :fill %>')">

    Cocktail name: <%= @cocktail.name %>
    <%= link_to "Delete Cocktail", delete_cocktail_path(@cocktail),:method => :delete %>
    <% @cocktail.doses.each do |dose| %>
      <div>
      Ingredient: <%= dose.ingredient.name %>, Dose: <%= dose.description %>
      <%= link_to "Delete Ingredient", delete_dose_path(dose),:method => :delete %>
      </div>
      <% end %>
</div>

<div class="row card-2">
<p>
<%= link_to "Add Dose", new_cocktail_dose_path(@cocktail)%>
<br>
<%= link_to "Back", cocktails_path %>
</p>
</div>
</div>

app/views/doses/_form.html.erb
<div class="banner" style="background-image: url('https://image.freepik.com/free-photo/watermelon-juice-with-copy-space_23-2147640789.jpg');">
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: Ingredient.all %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/new.html.erb
<h1>new dose</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <div class="title">
    <h1 style="color: #00bcd4;"><span>Alcoholic Choco's Cocktails</span></h1>
  </div>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Add Cocktail", new_cocktail_path , class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->

  </div>

  <!-- Dropdown list appearing on mobile only -->

</div>